name: .NET Core Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Cargohub.sln
      Test_Project_Path: Cargo\Tests\Tests.csproj
      Wap_Project_Directory: your-wap-project-directory-name
      Wap_Project_Path: your-wap-project-path

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install .NET Core SDK
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Set up MSBuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # Step 1: Start the server
      - name: Run the server
        run: |
          # Run your server in the background
          dotnet run --project Cargo\api\Cargo.csproj &
          # Wait for the server to start
          echo "Waiting for server to be ready..."
          sleep 20  # Increase this if necessary

      # Optional: Check if the server is up
      - name: Check server availability
        run: |
          curl --silent --fail http://localhost:3000 || (echo "Server not available" && exit 1)

      # Step 2: Run unit tests
      - name: Run Unit Test with Server
        run: |
          dotnet test

      # Optional: Stop the server
      - name: Stop Server
        run: |
          taskkill /f /im dotnet.exe
